### ISSUE TITLE
需要 internal 参数，以便上传删除等 Update 动作能走阿里云局域网

### ISSUE THREAD

**Issue by huacnlee** [aliyun-beta/aliyun-oss-ruby-sdk#5]

**Comment by zlx** [comment]
具体怎么使用？

**Comment by huacnlee** [comment]
域名后面加 -internal

https://github.com/huacnlee/carrierwave-aliyun/commit/b50792ffc77c6f2669bebc5600359bb0062f29da#diff-1941a04560821549ffb5f61d4b3750f1L108

**Comment by zlx** [comment]
这是仅限于上传／删除等 Update 操作还是全部操作？有相关参考文档吗？

**Comment by huacnlee** [comment]
主要是上传，这样能用内部网络带宽，速度更快，也不回占用外部带宽  


在 2016年2月14日 星期日，22:06，Newell Zhu 写道：

**Comment by zlx** [comment]
可以直接配置 Host 为内网地址

**Comment by zlx** [comment]
另外可以使用直接上传到 Aliyun OSS: https://github.com/aliyun-beta/aliyun-oss-ruby-sdk#directly-post-file-to-aliyun-oss

**Comment by huacnlee** [comment]
那样不行，我试过了，如果是 private 的空间，会因为上传的时候 host 用于签名的信息是 internal，而下载却是 public 的地址而签名验证无法通过

**Comment by zlx** [comment]
签名的时候好像并不需要 Host 信息，你是如何实现签名的

**Comment by huacnlee** [comment]
没签名啊，你看 carrierwave-aliyun 里面都是直接调 aliyun-oss-ruby-sdk 的

**Comment by zlx** [comment]
那可以提供一下下载时候你返回的错误信息，我尝试重现一下

**Comment by huacnlee** [comment]
```
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>
The request signature we calculated does not match the signature you provided. Check your key and signing method.
</Message>
<RequestId>56C13766CA2A04895ADBE8AE</RequestId>
<HostId>dianjihe.oss-cn-beijing.aliyuncs.com</HostId>
<OSSAccessKeyId>Y6B9ypM8Pkb73QmY</OSSAccessKeyId>
<SignatureProvided>usRdjuk9n s1Q4M uMzSTEMsSww=</SignatureProvided>
<StringToSign>
GET 1455506803 /dianjihe/attachment/2016/4d3b1137da80d949a183404a437f6ca8.png
</StringToSign>
<StringToSignBytes>
47 45 54 0A 0A 0A 31 34 35 35 35 30 36 38 30 33 0A 2F 64 69 61 6E 6A 69 68 65 2F 61 74 74 61 63 68 6D 65 6E 74 2F 32 30 31 36 2F 34 64 33 62 31 31 33 37 64 61 38 30 64 39 34 39 61 31 38 33 34 30 34 61 34 33 37 66 36 63 61 38 2E 70 6E 67
</StringToSignBytes>
</Error>
```

**Comment by zlx** [comment]
你使用过的方法是： [client#bucket_get_object](https://github.com/aliyun-beta/aliyun-oss-ruby-sdk/blob/master/lib/aliyun/oss/api/bucket_objects.rb#L117-L122)

**Comment by huacnlee** [comment]
bucket_get_object_share_link

**Comment by zlx** [comment]
阿里云的控制台生成的 URL 可以使用吗？

**Comment by zlx** [comment]
@huacnlee  怎么样，问题解决了吗？
按照你的意思，上传走内部网络，下载走公网，不知道理论是否可行。
我现在没有环境，能否帮我测试一下，这种情况下阿里云控制台生成的下载链接能不能用？

**Comment by huacnlee** [comment]
先别管吧，现在没需求，等有需要的时候我来实现好了

**Comment by zlx** [comment]
:+1:
